### PR TITLE
Fix glyph errors caught at validation

### PR DESCRIPTION
**Pull request by kaBeech**
I was just fixing a bunch of similar errors for my font, so I thought I might do yours as well 😸

Fixes self-intersections, bad directions, and points missing at extrema.

There are some self-intersections left, but I did the ones that didn't require manual adjustment.

Thanks for maintaining this awesome font!

### CODE REVIEW

**Comment by jesusmgg** [comment]
This got some conflicts after merging https://github.com/jesusmgg/comic-shanns-mono/pull/10, can you update the branch?

**Comment by kaBeech** [comment]
Thank you! Will fix after work tonight!

**Comment by kaBeech** [comment]
Fixed!

I also went ahead and fixed all remaining self-intersections, missing points at extrema, 
and non-integer coordinates, with the exception of the ∄ glyph

Thanks again!

**Comment by jesusmgg** [comment]
Thank you very much! This is an amazing addition.

**Comment by jesusmgg** [comment]
I will make a new release probably next week or the next one with all of the accumulated changes.

**Comment by sunshine-syz** [comment]
Could you also update the nerd font version?

**Comment by kaBeech** [comment]
@sunshine-syz IIRC Nerd Fonts will automatically check release versions of their upstream fonts and pull in the updates ahead of their next release. So once Jesús releases a new version we'll have to wait for NF to release their new version

In the meantime you can [patch it yourself](https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#font-patcher) or try [Serious Shanns](https://github.com/kaBeech/serious-shanns), my sister fork (which has some glyph changes but misses some characters in Comic Shanns Mono) which I applied the same fixes to =)

**Pull request merged**
